### ISSUE TITLE
Failed install of pdf2bib

### ISSUE THREAD

**Issue by ghost** [MicheleCotrufo/pdf2bib#18]
See attached installation log files.

/Frank

[Install log pymupdf.txt](https://github.com/user-attachments/files/16454646/Install.log.pymupdf.txt)
[Install log.txt](https://github.com/user-attachments/files/16454647/Install.log.txt)

**Comment by MicheleCotrufo** [comment]
This is due to a problem with the version of `pymupdf` required by the last version of `pdf2doi`. The solution is the same as in this other issue https://github.com/MicheleCotrufo/pdf-renamer/issues/20 .
We will fix the dependencies of `pdf2doi` soon

**Comment by MicheleCotrufo** [comment]
This should be fixed with version 1.7 of `pdf2doi` (just published), please re-open the issue if the problem persists.
